"
A ORActionAddVHost is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddVHost,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'channels',
		'pulseName',
		'node',
		'tracing',
		'sources',
		'users',
		'queues',
		'connections',
		'permissions',
		'creationDate',
		'bindings',
		'exchanges',
		'deletionDate'
	],
	#category : #'OrionPulseEntities-Action'
}
