"
A ORActionAddAuthentification is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddAuthentification,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'pulseName',
		'failureError',
		'timestamp',
		'success',
		'sources',
		'user'
	],
	#category : #'OrionPulseEntities-Action'
}
