"
A ORActionAddChannel is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddChannel,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'publisherComponent',
		'prefetchCount',
		'idleSince',
		'pulseState',
		'pulseName',
		'consumerProcess',
		'sources',
		'connection',
		'guaranteeMode',
		'globalPrefetchCount',
		'vhost',
		'user',
		'user_who_performed_connection',
		'pid',
		'consumerComponent',
		'closingDate',
		'creationDate',
		'consumedQueues'
	],
	#category : #'OrionPulseEntities-Action'
}
