"
A ORActionAddConnection is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddConnection,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'host',
		'channels',
		'port',
		'pulseState',
		'pulseName',
		'authMechanism',
		'protocol',
		'ssl',
		'connectedAt',
		'connectionType',
		'sslProtocol',
		'sources',
		'vhost',
		'user',
		'peerHost',
		'user_who_performed_connection',
		'pid',
		'closingDate',
		'creationDate',
		'sslHash',
		'peerPort'
	],
	#category : #'OrionPulseEntities-Action'
}
