"
A ORActionAddNodeType is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddNodeType,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'pulseState',
		'pulseName',
		'nodes',
		'sources'
	],
	#category : #'OrionPulseEntities-Action'
}
