"
A ORActionAddComponentType is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddComponentType,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'publisherComponents',
		'pulseState',
		'pulseName',
		'consumerComponents',
		'sources'
	],
	#category : #'OrionPulseEntities-Action'
}
