"
A ORActionAddBinding is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddBinding,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'pulseName',
		'sources',
		'source',
		'vhost',
		'routingKey',
		'creationDate',
		'deletionDate'
	],
	#category : #'OrionPulseEntities-Action'
}
