"
A ORActionAddPublisherComponent is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddPublisherComponent,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'address',
		'pulseState',
		'componentType',
		'pulseName',
		'tenantId',
		'owner',
		'guid',
		'usedChannels',
		'author',
		'appId',
		'platform',
		'sources',
		'deploymentMode',
		'messagesFromPublisher',
		'version',
		'exchanges'
	],
	#category : #'OrionPulseEntities-Action'
}
