"
A ORActionAddUser is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddUser,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'authentifications',
		'pulseName',
		'usedChannels',
		'initializedChannels',
		'sources',
		'vhosts',
		'passwordHash',
		'roles',
		'initializedExchanges',
		'passwordChangingDate',
		'initializedConnections',
		'passwordClearingDate',
		'usedConnections',
		'permissions',
		'creationDate',
		'deletionDate',
		'password',
		'hashingAlgorithm'
	],
	#category : #'OrionPulseEntities-Action'
}
