"
A ORActionAddExchangeFormat is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddExchangeFormat,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'exchangeFormatSchema',
		'pulseName',
		'sources',
		'messages',
		'exchangeFormatType'
	],
	#category : #'OrionPulseEntities-Action'
}
