"
A ORActionAddState is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddState,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'channels',
		'publisherComponents',
		'pulseState',
		'pulseName',
		'consumerComponents',
		'sources',
		'consumerProcesses',
		'queues',
		'connections'
	],
	#category : #'OrionPulseEntities-Action'
}
