"
A ORActionAddNode is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddNode,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'host',
		'port',
		'pulseName',
		'type',
		'running',
		'size_byte',
		'sources',
		'vhosts',
		'creationDate',
		'cluster',
		'deletionDate'
	],
	#category : #'OrionPulseEntities-Action'
}
