"
A ORActionAddPermission is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionAddPermission,
	#superclass : #ORActionAddEntity,
	#instVars : [
		'pulseName',
		'writeValue',
		'sources',
		'configureValue',
		'vhost',
		'readValue',
		'user',
		'creationDate',
		'deletionDate'
	],
	#category : #'OrionPulseEntities-Action'
}
