Extension { #name : #PulseUser }

{ #category : #'*OrionPulseCore' }
PulseUser >> privateAuthentifications [
	^ authentifications
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateAuthentifications: anObject [
	authentifications := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateCreationDate [
	^ creationDate
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateCreationDate: anObject [
	creationDate := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateDeletionDate [
	^ deletionDate
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateDeletionDate: anObject [
	deletionDate := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateHashingAlgorithm [
	^ hashingAlgorithm
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateHashingAlgorithm: anObject [
	hashingAlgorithm := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateInitializedChannels [
	^ initializedChannels
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateInitializedChannels: anObject [
	initializedChannels := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateInitializedConnections [
	^ initializedConnections
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateInitializedConnections: anObject [
	initializedConnections := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateInitializedExchanges [
	^ initializedExchanges
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateInitializedExchanges: anObject [
	initializedExchanges := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePassword [
	^ password
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePassword: anObject [
	password := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePasswordChangingDate [
	^ passwordChangingDate
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePasswordChangingDate: anObject [
	passwordChangingDate := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePasswordClearingDate [
	^ passwordClearingDate
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePasswordClearingDate: anObject [
	passwordClearingDate := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePasswordHash [
	^ passwordHash
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePasswordHash: anObject [
	passwordHash := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePermissions [
	^ permissions
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privatePermissions: anObject [
	permissions := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateRoles [
	^ roles
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateRoles: anObject [
	roles := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateUsedChannels [
	^ usedChannels
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateUsedChannels: anObject [
	usedChannels := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateUsedConnections [
	^ usedConnections
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateUsedConnections: anObject [
	usedConnections := anObject
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateVhosts [
	^ vhosts
]

{ #category : #'*OrionPulseCore' }
PulseUser >> privateVhosts: anObject [
	vhosts := anObject
]
