Extension { #name : #PulseVHost }

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateBindings [
	^ bindings
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateBindings: anObject [
	bindings := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateChannels [
	^ channels
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateChannels: anObject [
	channels := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateConnections [
	^ connections
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateConnections: anObject [
	connections := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateCreationDate [
	^ creationDate
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateCreationDate: anObject [
	creationDate := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateDeletionDate [
	^ deletionDate
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateDeletionDate: anObject [
	deletionDate := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateExchanges [
	^ exchanges
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateExchanges: anObject [
	exchanges := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateNode [
	^ node
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateNode: anObject [
	node := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privatePermissions [
	^ permissions
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privatePermissions: anObject [
	permissions := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateQueues [
	^ queues
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateQueues: anObject [
	queues := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateTracing [
	^ tracing
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateTracing: anObject [
	tracing := anObject
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateUsers [
	^ users
]

{ #category : #'*OrionPulseCore' }
PulseVHost >> privateUsers: anObject [
	users := anObject
]
