Extension { #name : #RMQUser }

{ #category : #'*OrionPulseCore' }
RMQUser >> privateAuthentifications [
	^ authentifications
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateAuthentifications: anObject [
	authentifications := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateCreationDate [
	^ creationDate
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateCreationDate: anObject [
	creationDate := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateDeletionDate [
	^ deletionDate
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateDeletionDate: anObject [
	deletionDate := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateHashingAlgorithm [
	^ hashingAlgorithm
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateHashingAlgorithm: anObject [
	hashingAlgorithm := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateInitializedChannels [
	^ initializedChannels
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateInitializedChannels: anObject [
	initializedChannels := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateInitializedConnections [
	^ initializedConnections
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateInitializedConnections: anObject [
	initializedConnections := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateInitializedExchanges [
	^ initializedExchanges
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateInitializedExchanges: anObject [
	initializedExchanges := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePassword [
	^ password
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePassword: anObject [
	password := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePasswordChangingDate [
	^ passwordChangingDate
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePasswordChangingDate: anObject [
	passwordChangingDate := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePasswordClearingDate [
	^ passwordClearingDate
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePasswordClearingDate: anObject [
	passwordClearingDate := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePasswordHash [
	^ passwordHash
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePasswordHash: anObject [
	passwordHash := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePermissions [
	^ permissions
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privatePermissions: anObject [
	permissions := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateRoles [
	^ roles
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateRoles: anObject [
	roles := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateUsedChannels [
	^ usedChannels
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateUsedChannels: anObject [
	usedChannels := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateUsedConnections [
	^ usedConnections
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateUsedConnections: anObject [
	usedConnections := anObject
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateVhosts [
	^ vhosts
]

{ #category : #'*OrionPulseCore' }
RMQUser >> privateVhosts: anObject [
	vhosts := anObject
]
