Extension { #name : #RMQVHost }

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateBindings [
	^ bindings
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateBindings: anObject [
	bindings := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateChannels [
	^ channels
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateChannels: anObject [
	channels := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateConnections [
	^ connections
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateConnections: anObject [
	connections := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateCreationDate [
	^ creationDate
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateCreationDate: anObject [
	creationDate := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateDeletionDate [
	^ deletionDate
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateDeletionDate: anObject [
	deletionDate := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateExchanges [
	^ exchanges
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateExchanges: anObject [
	exchanges := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateNode [
	^ node
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateNode: anObject [
	node := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privatePermissions [
	^ permissions
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privatePermissions: anObject [
	permissions := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateQueues [
	^ queues
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateQueues: anObject [
	queues := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateTracing [
	^ tracing
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateTracing: anObject [
	tracing := anObject
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateUsers [
	^ users
]

{ #category : #'*OrionPulseCore' }
RMQVHost >> privateUsers: anObject [
	users := anObject
]
